### ISSUE TITLE
Error when loading model

### ISSUE THREAD

**Issue by cjager** [fumitoh/modelx#41]
Hi,

I'm getting an error when trying to load my model, it has worked fine until now and also old versions that has worked before has stopped working...

I have tried to uninstall modelx/spyder modelx as well as running it in another environment but with the same result, see execution below.

Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.19.0 -- An enhanced Interactive Python.

Restarting kernel... 

 import modelx as mx

model=mx.read_model("A:/Christian/Modeller/CF-model/Company/V0.2")
Traceback (most recent call last):

  File "<ipython-input-2-c3934db42e87>", line 1, in <module>
    model=mx.read_model("A:/Christian/Modeller/CF-model/Company/V0.2")

  File "C:\Users\csalmeron\AppData\Local\Continuum\anaconda3\lib\site-packages\modelx\core\api.py", line 646, in read_model
    return _serialize.read_model(_system, model_path, name=name)

  File "C:\Users\csalmeron\AppData\Local\Continuum\anaconda3\lib\site-packages\modelx\serialize\__init__.py", line 123, in read_model
    system, path).read_model(**kwargs)

  File "C:\Users\csalmeron\AppData\Local\Continuum\anaconda3\lib\site-packages\modelx\serialize\serializer_4.py", line 1037, in read_model
    model = self._read_model_inner()

  File "C:\Users\csalmeron\AppData\Local\Continuum\anaconda3\lib\site-packages\modelx\serialize\serializer_4.py", line 1064, in _read_model_inner
    self.read_pickledata()

  File "C:\Users\csalmeron\AppData\Local\Continuum\anaconda3\lib\site-packages\modelx\serialize\serializer_4.py", line 1151, in read_pickledata
    custom_load, file, "b")

  File "C:\Users\csalmeron\AppData\Local\Continuum\anaconda3\lib\site-packages\modelx\serialize\ziputil.py", line 366, in read_file_utf8
    return read_file(callback, path, mode, encoding="utf-8", newline=newline)

  File "C:\Users\csalmeron\AppData\Local\Continuum\anaconda3\lib\site-packages\modelx\serialize\ziputil.py", line 362, in read_file
    return callback(f)

  File "C:\Users\csalmeron\AppData\Local\Continuum\anaconda3\lib\site-packages\modelx\serialize\serializer_4.py", line 1139, in custom_load
    return unpickler.load()

  File "C:\Users\csalmeron\AppData\Local\Continuum\anaconda3\lib\site-packages\modelx\io\baseio.py", line 220, in __setstate__
    self._on_unserialize(state)

  File "C:\Users\csalmeron\AppData\Local\Continuum\anaconda3\lib\site-packages\modelx\io\pandasio.py", line 133, in _on_unserialize
    self._read_pandas()

  File "C:\Users\csalmeron\AppData\Local\Continuum\anaconda3\lib\site-packages\modelx\io\pandasio.py", line 141, in _read_pandas
    self._data.load_from, **self._read_args)

  File "C:\Users\csalmeron\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\excel\_base.py", line 304, in read_excel
    io = ExcelFile(io, engine=engine)

  File "C:\Users\csalmeron\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\excel\_base.py", line 821, in __init__
    self._reader = self._engines[engine](self._io)

  File "C:\Users\csalmeron\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\excel\_openpyxl.py", line 485, in __init__
    super().__init__(filepath_or_buffer)

  File "C:\Users\csalmeron\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\excel\_base.py", line 353, in __init__
    self.book = self.load_workbook(filepath_or_buffer)

  File "C:\Users\csalmeron\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\excel\_openpyxl.py", line 497, in load_workbook
    filepath_or_buffer, read_only=True, data_only=True, keep_links=False

  File "C:\Users\csalmeron\AppData\Local\Continuum\anaconda3\lib\site-packages\openpyxl\reader\excel.py", line 313, in load_workbook
    data_only, keep_links)

  File "C:\Users\csalmeron\AppData\Local\Continuum\anaconda3\lib\site-packages\openpyxl\reader\excel.py", line 124, in __init__
    self.archive = _validate_archive(fn)

  File "C:\Users\csalmeron\AppData\Local\Continuum\anaconda3\lib\site-packages\openpyxl\reader\excel.py", line 96, in _validate_archive
    archive = ZipFile(filename, 'r')

  File "C:\Users\csalmeron\AppData\Local\Continuum\anaconda3\lib\zipfile.py", line 1258, in __init__
    self._RealGetContents()

  File "C:\Users\csalmeron\AppData\Local\Continuum\anaconda3\lib\zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")

BadZipFile: File is not a zip file

**Comment by fumitoh** [comment]
This issue has been resolved offline.
