### ISSUE TITLE
Zipping model to network location: access issue

### ISSUE THREAD

**Issue by alexeybaran** [fumitoh/modelx#82]
From time to time I get an error, when zipping several models to the network location. I suspect it is due to modelx writing several times to the same zip file: first time to create structure of folders and later to fill it in with data. During the first writing, the access to the file gets blocked for other applications and isn't always timely released, when the model tries writing to the same file again.

The workaround is:
```
with tempfile.TemporaryDirectory() as tempdir:
    for model_name, m in models.items():
        temp_path = tempdir + "/" + model_name + '.zip'
        m.zip(temp_path)
        target_path = subfolder + model_name + '.zip'
        shutil.move(temp_path, target_path)
```

**Comment by fumitoh** [comment]
Does the issue happens only when the models are getting saved  on a network location AND have data to be written to files in them (such as xlsx, csv)?

**Comment by alexeybaran** [comment]
It is difficult to reproduce. I only get this error when saving model several times with large number of csv files (~30). As you can see below it saves 2 time before breaking on the 3rd one.

```
import numpy as np
import pandas as pd
path = r'\\athfs03\actuarial\Pricing\Block and Flow Transactions\Tools and Templates\EPA Python\test'
m = mx.new_model()
d = pd.DataFrame(np.ones([100, 100]))
for i in range(0, 100):
    name = 'd' + str(i)
    m.new_pandas(name, name + '.csv', data=d, file_type='csv')
for i in range(0, 10):
    print(i)
    m.zip(path + '/m.zip')

0
1
2
Traceback (most recent call last):
  File "C:\Users\e73815\PycharmProjects\Python_EPA2\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3442, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-c7cbae61bd52>", line 15, in <module>
    m.zip(path + '/m.zip')
  File "C:\Users\e73815\PycharmProjects\Python_EPA2\venv\lib\site-packages\modelx\core\model.py", line 439, in zip
    write_model(self._impl.system, self, model_path, is_zip=True,
  File "C:\Users\e73815\PycharmProjects\Python_EPA2\venv\lib\site-packages\modelx\serialize\__init__.py", line 115, in write_model
    serializer.ModelWriter(system, model, root, log_input=log_input,
  File "C:\Users\e73815\PycharmProjects\Python_EPA2\venv\lib\site-packages\modelx\serialize\serializer_5.py", line 337, in write_model
    ziputil.copy_dir_to_zip(temproot, self.root,
  File "C:\Users\e73815\PycharmProjects\Python_EPA2\venv\lib\site-packages\modelx\serialize\ziputil.py", line 322, in copy_dir_to_zip
    copy_file(srcfile, destfile,
  File "C:\Users\e73815\PycharmProjects\Python_EPA2\venv\lib\site-packages\modelx\serialize\ziputil.py", line 292, in copy_file
    with zipfile.ZipFile(root_dst, mode="a",
  File "C:\Python64\3.9\lib\zipfile.py", line 1248, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: '\\\\athfs03\\actuarial\\Pricing\\Block and Flow Transactions\\Tools and Templates\\EPA Python\\test\\m.zip'
```

**Comment by fumitoh** [comment]
Your guess is probably right. But the bug seems to be in the zipfile standard library as the modelx code properly encloses every write operation in `with` statement to ensure that the file is closed after each write.
A quick-and-dirty fix would be to retry writing to the file some times til it successes.

Can you check if giving `backup=False`  to `m.zip` solves the problem? (I guess this is irrelevant but just in case.)

**Comment by alexeybaran** [comment]
v0.21 and v0.22 break with and without `backup=False`. Overall, writing zip file on the network is terribly slow, this approach is faster:
```
with tempfile.TemporaryDirectory() as tempdir:
    for model_name, m in models.items():
        temp_path = tempdir + "/" + model_name + '.zip'
        m.zip(temp_path)
        target_path = subfolder + model_name + '.zip'
        shutil.move(temp_path, target_path)
```


Error message from v0.22:
```
0
UserWarning: writing to '%s' failed, retrying...
1
2
3
4
5
Traceback (most recent call last):
  File "C:\Users\e73815\PycharmProjects\Python_EPA2\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3442, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-5c9961dcf460>", line 1, in <module>
    runfile('C:/Users/e73815/PycharmProjects/Python_EPA2/try_bokeh.py', wdir='C:/Users/e73815/PycharmProjects/Python_EPA2')
  File "C:\Program Files\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/e73815/PycharmProjects/Python_EPA2/try_bokeh.py", line 12, in <module>
    m.zip(path + '/m.zip',backup=False)
  File "C:\Users\e73815\PycharmProjects\Python_EPA2\venv\lib\site-packages\modelx\core\model.py", line 439, in zip
    write_model(self._impl.system, self, model_path, is_zip=True,
  File "C:\Users\e73815\PycharmProjects\Python_EPA2\venv\lib\site-packages\modelx\serialize\__init__.py", line 77, in write_model
    ziputil.write_str(json.dumps(
  File "C:\Users\e73815\PycharmProjects\Python_EPA2\venv\lib\site-packages\modelx\serialize\ziputil.py", line 160, in write_str
    write_file(lambda f: f.write(string), path, mode="t",
  File "C:\Users\e73815\PycharmProjects\Python_EPA2\venv\lib\site-packages\modelx\serialize\ziputil.py", line 231, in write_file
    with zipfile.ZipFile(
  File "C:\Python64\3.9\lib\zipfile.py", line 1248, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'XXX\\m.zip'
```

**Comment by alexeybaran** [comment]
It also seems that after failing and retrying to write zip, part of the files initially written gets lost:
![image](https://github.com/fumitoh/modelx/assets/52170315/9fd27f6a-aba3-4f9f-a1c2-c144575d8acb)

**Comment by fumitoh** [comment]
Maybe the workaound was a bad idea. I'll remove it and think about how your suggested approach can be reflected.

**Comment by fumitoh** [comment]
@alexeybaran modelx 0.23.0 creates a local zip file in the temp dir and copies it to the destination as you suggested.

**Comment by alexeybaran** [comment]
It works perfectly. Thank you very much!
